server:
  servlet.path: /
  error:
    include-exception: true
    include-stacktrace: always
    path: /error.jsp
    whitelabel.enabled: true

spring:
  devtools:
    livereload.enabled: true
  mvc:
    servlet.load-on-startup: -1
    view.prefix: /WEB-INF/jsp/
    view.suffix: .jsp
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
